{
  holders (where: { address: "0x79561db79bdb335a1eb9657fed42ad914c995b99" }) {
    distributor {
      address
    }
  }
}

{
  creator: assetOwnerships (where: { creatorBeneficiary: "0x79561db79bdb335a1eb9657fed42ad914c995b99" }) {
    asset {
      assetId
      template {
        templateId
      }
      engine
      actor
    }
  },
  counterparty: assetOwnerships (where: { counterpartyBeneficiary: "0x79561db79bdb335a1eb9657fed42ad914c995b99" }) {
    asset {
      assetId
      template {
        templateId
      }
      engine
      actor
    }
  }
}

{
  assets(first: 10) {
    assetId
  }
}

{
  assets(first: 1) {
    assetId
    template {
      templateId
    }
    engine
    actor
    ownership {
      creatorObligor
      creatorBeneficiary
      counterpartyObligor
      counterpartyBeneficiary
    }
    lifecycleTerms {
      calendar
      contractRole
      dayCountConvention
      businessDayConvention
      endOfMonthConvention
      scalingEffect
      penaltyType
      feeBasis
      creditEventTypeCovered
      contractReference_1 {
        object
        _type
        role
      }
      contractReference_2 {
        object
        _type
        role
      }
      currency
      settlementCurrency
      marketObjectCodeRateReset
      statusDate
      maturityDate
      notionalPrincipal
      nominalInterestRate
      feeAccrued
      accruedInterest
      rateMultiplier
      rateSpread
      feeRate
      nextResetRate
      penaltyRate
      premiumDiscountAtIED
      priceAtPurchaseDate
      nextPrincipalRedemptionPayment
      coverageOfCreditEnhancement
      gracePeriod {
        i
        p
        isSet
      }
      delinquencyPeriod {
        i
        p
        isSet
      }
      lifeCap
      lifeFloor
      periodCap
      periodFloor
    }
    state {
      contractPerformance
      statusDate
      nonPerformingDate
      maturityDate
      exerciseDate
      notionalPrincipal
      accruedInterest
      feeAccrued
      nominalInterestRate
      interestScalingMultiplier
      notionalScalingMultiplier
      nextPrincipalRedemptionPayment
      exerciseAmount
    
    }
    anchorDate
    nextScheduledEvent
    nextScheduleIndex
  }
}

{
  templates(first: 10) {
    templateId
  }
}

{
  templates(first: 1) {
    templateId
    templateTerms {
      calendar
      contractRole
      dayCountConvention
      businessDayConvention
      endOfMonthConvention
      scalingEffect
      penaltyType
      feeBasis
      creditEventTypeCovered
      currency
      settlementCurrency
      marketObjectCodeRateReset
      statusDateOffset
      maturityDateOffset
      feeAccrued
      accruedInterest
      rateMultiplier
      feeRate
      nextResetRate
      penaltyRate
      priceAtPurchaseDate
      nextPrincipalRedemptionPayment
      gracePeriod {
        i
        p
        isSet
      }
      delinquencyPeriod {
        i
        p
        isSet
      }
      periodCap
      periodFloor
    }
    templateSchedule
  }
}
