{
  holders (where: { address: "0x79561db79bdb335a1eb9657fed42ad914c995b99" }) {
    distributor {
      address
    }
  }
}

{
  creator: assetOwnerships (where: { creatorBeneficiary: "0x79561db79bdb335a1eb9657fed42ad914c995b99" }) {
    asset {
      assetId
      engine
      actor
    }
  },
  counterparty: assetOwnerships (where: { counterpartyBeneficiary: "0x79561db79bdb335a1eb9657fed42ad914c995b99" }) {
    asset {
      assetId
      engine
      actor
    }
  }
}

{
  assets(first: 10) {
    assetId
  }
}

{
  assets(first: 1) {
    assetId
    engine
    actor
    ownership {
      creatorObligor
      creatorBeneficiary
      counterpartyObligor
      counterpartyBeneficiary
    }
    state {
      contractPerformance
      statusDate
      nonPerformingDate
      maturityDate
      exerciseDate
      notionalPrincipal
      accruedInterest
      feeAccrued
      nominalInterestRate
      interestScalingMultiplier
      notionalScalingMultiplier
      nextPrincipalRedemptionPayment
      exerciseAmount
    
    }
    schedule {
      pendingEvent
      nextScheduledEvent
    }
  }
}
